//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGo.RocketAPI.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGo.RocketAPI.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downArrow {
            get {
                object obj = ResourceManager.GetObject("downArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;Pokedex&gt;
        ///  &lt;Pokemon Index=&quot;001&quot; name=&quot;Bulbasaur&quot;&gt;
        ///    &lt;Type1&gt;Grass&lt;/Type1&gt;
        ///    &lt;Type2&gt;Poison&lt;/Type2&gt;
        ///  &lt;/Pokemon&gt;
        ///  &lt;Pokemon Index=&quot;002&quot; name=&quot;Ivysaur&quot;&gt;
        ///    &lt;Type1&gt;Grass&lt;/Type1&gt;
        ///    &lt;Type2&gt;Poison&lt;/Type2&gt;
        ///  &lt;/Pokemon&gt;
        ///  &lt;Pokemon Index=&quot;003&quot; name=&quot;Venusaur&quot;&gt;
        ///    &lt;Type1&gt;Grass&lt;/Type1&gt;
        ///    &lt;Type2&gt;Poison&lt;/Type2&gt;
        ///  &lt;/Pokemon&gt;
        ///  &lt;Pokemon Index=&quot;004&quot; name=&quot;Charmander&quot;&gt;
        ///    &lt;Type1&gt;Fire&lt;/Type1&gt;
        ///  &lt;/Pokemon&gt;
        ///  &lt;Pokemon Index=&quot;005&quot; name=&quot;Charmeleon&quot;&gt;
        ///    &lt;Type1&gt;Fire&lt;/Type1&gt;
        ///  &lt;/Po [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PokedexPokemonTypes {
            get {
                return ResourceManager.GetString("PokedexPokemonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upArrow {
            get {
                object obj = ResourceManager.GetObject("upArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
